language: node_js
node_js:
- 8.17.0
- 9.11.2
- 10.22.0
- 11.15.0
- 12.18.2
- 13.14.0
after_success: "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
notifications:
  email: false
  slack:
    rooms:
      secure: EqiJVewhfLpKIXB9RxzGGblWe4yA+W7ORaaWBqYwOt6R6R1Bg0Kd57h+F18CHNSu0IqXaxVB4slnH7+8AnqX/CpGffqSIdX5gMNsJxyXJGK2sNK+kjMQ3su+RIuBWZWxPcGpQ9Xl9/iZf1tVSdTZGnwcPl+rch4VtWqr7AQnVpPH/7f5FR+Hi2U2sjYGQO+YvFk4qqToe0GCTTLHd+2mcyAWMxLAnrJXqUx91PafRZtf7mqIQC0zoAm+mq/1vkKnDIqBREfe1TdJ0vVIG4c4CNDSX0/xbGUSCSDj8ZD9eyg9ila01cM860OCIs1f4f8nGBhTG1KphV2wglHfl/9TbjMXrr9kCT+fObfCcBhryqa4ZrbkHMupLpFCQFRC0afNJFkIBEySLsm+LbWrfTtuYlLRa7ckgnLHJHcQQthfYnzOi1h9D7v6NZBbzqVvVdBT+IPL9PEPcosHujFff6f/a4FlLVcTgu+KMWlK6mbX8/C7BUBw0sFix2xt6wTBSUG2VFI9c0uDSgMg3KubUwNbWVQqa39jwTN8kKG3hIqj3dFzmC1q9UQncMrSepEG86IHHdV2NfnQdWYeKsXeTPgHbIlXzL8WrzNyudFY7fCNcIcihLKZW4RlBVqb2tqXCFp9Py9wqpml/JAJV5UDF9stpUMo5fT2FrbtBjBq7K/1bOs=
