language: node_js
node_js:
- 8.9.4
notifications:
  slack:
    secure: BkcKpa/FAbqzHuLEbPxNAQ4sSCeMA0e/gtMJqxL2j1m6OwpadYN+S3a1xv7Xh0wZkA2mnXC1dYEzsZb+dFvHYICVv3Jz6Pi7ALmVnRhFHCYDAS5+hgaxwCt6x2Yr8+/0MPZF8R7A7hex98lA05V9nSuhslcVPfdjmgbPpIMcIRx7IryU5mfZtx/uKd0UtaMgpK326CJ6y/RYbhbTeYkXKmXYaygdBdUU8B24Z2y/x3N+75ZdUY2JfPEgpt9i1UDhVv9sNoWog3L5wSlxHjiTIvazl17/7eEUwTnyIwXiuJgaMqQBrSTcKssJJnvDZZoLnWQVwkmRUQ2uXVq19TR7TCQWUTZ41ABURt8PfouJV43emDSJmQKzPP0eENig7uORkODeHQIxCtnumt8flyLiUJ5Uohm1wiq0xwCaPCVz5wCCP+4v/drUuZ+iWq68PCUBdJyERkJxZZuYXGUC/iGX+qqOJYIdNgQswUFZbpkb9OW38t2fMc10YzYJsfEZIZ/EF3BI5/XHRASXssWatHtWFyHYFEdL3pAFfMpc7fNFyqB90Dj9YdLHRDc257sAl9iukjQ4jup3Kav/A+ssTHbgjQA1RePw8VmqjexRGc9iGuiTLQb64FS4gMLQy+0fGmVgr0pX0V5izrBqkV9yhn3AAEKpgFfb1c9GE13aAfttCgQ=
